# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkvEVmS7Pm8yZsvcIaH95umB3jOkTbyj

df = pd.read_excel('cancer_data.xlsx')

df.head()
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('res_dpre.csv')
df.head()

df.shape

df.columns

df['diagnosis'].unique()

# "M" → Malignant (cancerous, harmful, and likely to spread)
# "B" → Benign (non-cancerous, generally not harmful, and does not spread)

# Fractal dimension in cancer tumors is a mathematical measure used to describe
#the complexity and irregularity of tumor shapes and structures. It quantifies
#how detail in a tumor’s shape changes with scale

df.describe()

sns.pairplot(df); # correlation

df.hist(figsize=(15,15));

df_m = df[df['diagnosis']=='M']
df_b = df[df['diagnosis']=='B']

df_m['perimeter_mean'].hist(alpha=0.5); #blue
df_b['perimeter_mean'].hist(alpha=0.5); # orange

df_b.hist(figsize=(15,15));

df_m.hist(figsize=(15,15));

insight1 = "the size of the tumor increases its danger (area) "
insight2 = "concavity in tumors often exist in Malignant cases "
insight3 = " Malignant Tumors with irregular, invasive growth patterns tend to have higher fractal dimensions."

with open('eda-in-1.txt', 'w') as f:
    f.write(insight1)

with open('eda-in-2.txt', 'w') as f:
    f.write(insight2)

with open('eda-in-3.txt', 'w') as f:
    f.write(insight3)