# -*- coding: utf-8 -*-
"""vis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6u-WQhYOkOOKjAPtPKBN8iW3g9gZtpi
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('res_dpre.csv')
df.head()

df_m = df[df['diagnosis']=='M']
df_b = df[df['diagnosis']=='B']

# Select only numeric columns
numeric_cols = df_m.select_dtypes(include=['number']).columns
num_features = len(numeric_cols)

num_cols = 4  # Define number of columns
num_rows = (num_features + num_cols - 1) // num_cols  # Compute required rows (ceil division)

fig, axes = plt.subplots(nrows=num_rows, ncols=num_cols, figsize=(15, num_rows * 3))
axes = axes.flatten()  # Flatten the 2D array of axes

# Plot histograms in the correct order
for i, col in enumerate(numeric_cols):
    axes[i].hist(df_m[col], bins=30, alpha=0.5, color='red', label='Malignant')
    axes[i].hist(df_b[col], bins=30, alpha=0.5, color='blue', label='Benign')
    axes[i].set_title(col)
    axes[i].legend()

# Hide unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])  # Deletes empty subplot

plt.tight_layout()
plt.savefig("vis.png", dpi=300, bbox_inches='tight')  # High resolution & no extra whitespace

plt.show()